name: Download Cache

on:
  push:
    branches: [ "download-cache" ]

jobs:
  dump-cache:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, ARM64]
        include:
          - arch: x64
            triplet: x64-windows
            artifact: cache_dump_x64
          - arch: ARM64
            triplet: arm64-windows
            artifact: cache_dump_arm64
    steps:
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg/
        key: vcpkg-${{ runner.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-${{ matrix.triplet }}-

    - name: Archive cache
      run: |
        tar -czf cache.tar.gz -C "${{ github.workspace }}/vcpkg" .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: cache.tar.gz
